# Generated by Django 5.2.15 on 2026-06-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('product_code', models.CharField(blank=True, help_text='e.g. STAGSURF D33', max_length=50)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('technical_specifications', models.TextField(blank=True)),
                ('application_details', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('properties', models.TextField(blank=True)),
                ('formulation_type', models.CharField(choices=[('SC', 'SC Formulation'), ('EC', 'EC Formulation'), ('ME', 'ME Formulation'), ('EW', 'EW Formulation'), ('ADJUVANT', 'Adjuvant'), ('WETTING', 'Wetting Agent'), ('DISPERSING', 'Dispersing Agent'), ('TEXTILE', 'Textile Chemical'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
