# Generated by Django 5.2.15 on 2026-06-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_meta_description_category_meta_title_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_text', models.CharField(max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'product metrics',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_value', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'product properties',
                'ordering': ['display_order', 'property_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='application_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.AlterField(
            model_name='product',
            name='formulation_type',
            field=models.CharField(choices=[('SC', 'SC Formulation'), ('EC', 'EC Formulation'), ('ME', 'ME Formulation'), ('EW', 'EW Formulation'), ('ADJUVANT', 'Adjuvant'), ('WETTING', 'Wetting Agent'), ('DISPERSING', 'Dispersing Agent'), ('TEXTILE', 'Textile Chemical'), ('CROP_PROTECTION', 'Crop Protection'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_specifications',
            field=models.TextField(blank=True, help_text='General technical overview (structured properties managed separately).'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['formulation_type'], name='products_pr_formula_75bbf0_idx'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='products.product'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='products.product'),
        ),
        migrations.AddField(
            model_name='productmetric',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='products.product'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='products.product'),
        ),
    ]
