# Generated by Django 5.2.15 on 2026-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('products', '0002_productapplication_productbenefit_productmetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='product_name',
            field=models.CharField(blank=True, help_text='Snapshot of product name at time of inquiry.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-created_at'], name='inquiries_i_created_2b1632_idx'),
        ),
    ]
