# Generated by Django 5.2.15 on 2026-06-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_product_name_and_more'),
        ('products', '0002_productapplication_productbenefit_productmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('product_page', 'Product Page'), ('contact_page', 'Contact Page')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Legacy notes field — use Inquiry Notes below.'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['source'], name='inquiries_i_source_5a7084_idx'),
        ),
        migrations.AddField(
            model_name='inquirynote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquirynote',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inquiries.inquiry'),
        ),
    ]
