# Generated by Django 5.2.15 on 2026-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('product_information', 'Product Information'), ('product_specific_inquiry', 'Product Specific Inquiry'), ('technical_support', 'Technical Support'), ('dealer_inquiry', 'Dealer Inquiry'), ('distributor_inquiry', 'Distributor Inquiry'), ('sample_request', 'Sample Request'), ('pricing_quotation', 'Pricing & Quotation'), ('partnership_opportunity', 'Partnership Opportunity'), ('other', 'Other')], help_text='Reason for contact selected on the website form.', max_length=50),
        ),
    ]
