# Generated by Django 5.2.15 on 2026-06-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('TDS', 'Technical Data Sheet'), ('BROCHURE', 'Brochure'), ('PDF', 'Product PDF'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Leave blank for general company documents.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
