# Generated by Django 5.2.15 on 2026-06-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('products', '0002_productapplication_productbenefit_productmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('TDS', 'Technical Data Sheet'), ('BROCHURE', 'Brochure'), ('CATALOG', 'Catalog'), ('MSDS', 'MSDS'), ('PRODUCT_SHEET', 'Product Sheet')], default='TDS', max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'document_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='documents.productdocument')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='TechnicalDocument',
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['document_type'], name='documents_p_documen_d3a986_idx'),
        ),
    ]
