# Generated by Django 5.2.15 on 2026-06-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_productdocument_documentdownloadlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('COMPANY_PROFILE', 'Company Profile'), ('COMPANY_BROCHURE', 'Company Brochure'), ('CERTIFICATE', 'Certificate'), ('TECHNICAL_CATALOG', 'Technical Catalog'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('pdf_file', models.FileField(upload_to='documents/company/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to='documents/products/'),
        ),
    ]
