"""Catalog data for Star Agsurf Industries — categories and products."""

from apps.products.models import Product

# (name, slug, description, display_order)
CATEGORIES = [
    ("Spreader", "spreader", "Specialty spreader products for spray applications.", 1),
    (
        "Performance Chemicals",
        "performance-chemicals",
        "Surfactants and performance chemicals for SC, WP, WDG, SL, and OD formulations.",
        2,
    ),
    (
        "Surfactants for Glyphosate SL",
        "surfactants-glyphosate-sl",
        "Emulsifiers and adjuvants for glyphosate soluble liquid (SL) formulations.",
        3,
    ),
    (
        "Emulsifier/Wetter/Dispersant for SC Formulations",
        "emulsifier-wetter-dispersant-sc",
        "Surfactants for suspension concentrate (SC) formulations across pH ranges.",
        4,
    ),
    (
        "Two Component System for All SC Formulations",
        "two-component-all-sc",
        "Two-component wetting and dispersing systems for all SC formulations.",
        5,
    ),
    (
        "Single Component System for Various SC Formulations",
        "single-component-various-sc",
        "Single-component surfactant systems for various SC formulations.",
        6,
    ),
    (
        "Single Component System for Bispyribac 10% Sodium",
        "single-component-bispyribac-10",
        "Single-component emulsifier system for Bispyribac SC 10% sodium.",
        7,
    ),
    (
        "Two Component System for Bispyribac 10% Sodium",
        "two-component-bispyribac-10",
        "Two-component wetting and dispersing system for Bispyribac SC 10% sodium.",
        8,
    ),
    (
        "Two Component System for Bispyribac 40% Sodium",
        "two-component-bispyribac-40",
        "Two-component wetting and dispersing system for Bispyribac SC 40% sodium.",
        9,
    ),
    (
        "Emulsifier/Wetter/Dispersant for EC Formulations",
        "emulsifier-wetter-dispersant-ec",
        "Emulsifiers and wetters for emulsifiable concentrate (EC) formulations.",
        10,
    ),
    (
        "Emulsifier/Dispersant for ME Formulation",
        "emulsifier-dispersant-me",
        "Emulsifiers for micro-emulsion (ME) formulations.",
        11,
    ),
    (
        "Emulsifier/Dispersant for CS Formulation",
        "emulsifier-dispersant-cs",
        "Emulsifiers for capsule suspension (CS) formulations.",
        12,
    ),
    (
        "Emulsifier/Dispersant for EW Formulation",
        "emulsifier-dispersant-ew",
        "Wetting and dispersing agents for emulsion-in-water (EW) formulations.",
        13,
    ),
    (
        "Penetrant/Wetting Agent for Various Dry and Wet Formulations",
        "penetrant-wetting-dry-wet",
        "Penetrant and wetting agents for dry and wet agrochemical formulations.",
        14,
    ),
    (
        "Single Component System Emulsifier for Glufosinate SL",
        "single-component-glufosinate-sl",
        "Single-component emulsifier for glufosinate soluble liquid (SL) formulations.",
        15,
    ),
    (
        "Wetter and Dispersant for Dry Formulations",
        "wetter-dispersant-dry-formulations",
        "Wetting and dispersing agents for WP, WDG, and dry formulation systems.",
        16,
    ),
    (
        "Proprietary Blends",
        "proprietary-blends",
        "Proprietary surfactant and adjuvant blends for crop protection.",
        17,
    ),
    ("Mercerisation", "textile-mercerisation", "Mercerising agents for cotton and blends.", 18),
    (
        "Wetting/Scouring/Stain Removing Agents",
        "textile-wetting-scouring",
        "Wetting, scouring, and stain removing agents for textile processing.",
        19,
    ),
    ("Dyeing Aids", "textile-dyeing-aids", "Dye fixing, washing, levelling, and soaping agents.", 20),
    ("Finishing Agents", "textile-finishing-agents", "Softeners and finishing agents for textile substrates.", 21),
]

# Legacy category slugs from the old seed — deactivated on full seed run.
LEGACY_CATEGORY_SLUGS = [
    "crop-protection",
    "sc-formulations",
    "ec-formulations",
    "me-formulations",
    "ew-formulations",
    "adjuvants",
    "wetting-agents",
    "dispersing-agents",
    "textile-chemicals",
]

# (name, slug, category_slug, formulation_type, product_code, equivalent, function, formulation, is_featured)
PRODUCTS = [
    # Spreader
    (
        "STAGSPREAD 4080",
        "stagspread-4080",
        "spreader",
        Product.FormulationType.OTHER,
        "STAGSPREAD 4080",
        "Silwet 408",
        "Spreader",
        "Spreader",
        False,
    ),
    # Performance Chemicals (brochure page 4)
    (
        "STAGSURF 425",
        "stagsurf-425",
        "performance-chemicals",
        Product.FormulationType.DISPERSING,
        "STAGSURF 425",
        "Sodium Naphthalene formaldehyde condensate",
        "Dispersant",
        "WP, WDG, SC",
        False,
    ),
    (
        "STAGSURF PD 137",
        "stagsurf-pd-137",
        "performance-chemicals",
        Product.FormulationType.DISPERSING,
        "STAGSURF PD 137",
        "Polycarboxylate based polymer",
        "Aqueous dispersant",
        "SC, SE",
        False,
    ),
    (
        "STAGWET SLS",
        "stagwet-sls",
        "performance-chemicals",
        Product.FormulationType.WETTING,
        "STAGWET SLS",
        "Sodium Lauryl Sulphate",
        "Wetting agent",
        "WP, SP, SG, WDG",
        False,
    ),
    (
        "STAGWET AOS",
        "stagwet-aos",
        "performance-chemicals",
        Product.FormulationType.WETTING,
        "STAGWET AOS",
        "Alpha Olefin Sulphonate",
        "Wetting agent",
        "WP, SP, SG, WDG",
        False,
    ),
    (
        "STAGSURF AG810",
        "stagsurf-ag810",
        "performance-chemicals",
        Product.FormulationType.WETTING,
        "STAGSURF AG810",
        "Alkyl Polyglucoside (C8-C10)",
        "Wetting agent",
        "SL",
        False,
    ),
    (
        "STAGWET WT 7200",
        "stagwet-wt-7200",
        "performance-chemicals",
        Product.FormulationType.WETTING,
        "STAGWET WT 7200",
        "Sodium dioctyl Sulphosuccinate (Liquid)",
        "Superwetting agent",
        "SC, WP, WDG",
        False,
    ),
    (
        "STAGWET ROE60",
        "stagwet-roe60",
        "performance-chemicals",
        Product.FormulationType.WETTING,
        "STAGWET ROE60",
        "Sodium dioctyl Sulphosuccinate in methyl ester",
        "Superwetting agent",
        "OD, SL",
        False,
    ),
    # Surfactants for Glyphosate SL (brochure page 4)
    (
        "STAGSURF TAE",
        "stagsurf-tae",
        "surfactants-glyphosate-sl",
        Product.FormulationType.ADJUVANT,
        "STAGSURF TAE",
        "Proprietary (Tallow based)",
        "Emulsifier/Adjuvant",
        "SL",
        False,
    ),
    (
        "STAGSURF NTAE",
        "stagsurf-ntae",
        "surfactants-glyphosate-sl",
        Product.FormulationType.ADJUVANT,
        "STAGSURF NTAE",
        "Proprietary (Non-Tallow based)",
        "Emulsifier/Adjuvant",
        "SL",
        False,
    ),
    # Emulsifier/Wetter/Dispersant for SC Formulations
    (
        "STAGSURF D33",
        "stagsurf-d33",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF D33",
        "Soprophor 3D 33",
        "Emulsifier/Dispersant",
        "SC, Low pH",
        False,
    ),
    (
        "STAGSURF TFL",
        "stagsurf-tfl",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF TFL",
        "Soprophor FL",
        "Emulsifier/Dispersant",
        "SC, Normal pH",
        False,
    ),
    (
        "STAGSURF TFLK",
        "stagsurf-tflk",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF TFLK",
        "Soprophor FLK",
        "Dispersant",
        "SC",
        False,
    ),
    (
        "STAGSURF 483",
        "stagsurf-483",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF 483",
        "Soprophor 4D384",
        "Emulsifier/Dispersant",
        "EC, SC, Low to Normal pH",
        False,
    ),
    (
        "STAGSURF TSU",
        "stagsurf-tsu",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF TSU",
        "Soprophor BSU",
        "Emulsifier/Dispersant",
        "EC, SC, Alkaline pH",
        False,
    ),
    (
        "STAGSURF EP 140",
        "stagsurf-ep-140",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF EP 140",
        "Pluronic PE 10400",
        "Low Foam Emulsifier",
        "SC, SE",
        False,
    ),
    (
        "STAGSURF EP 150",
        "stagsurf-ep-150",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF EP 150",
        "Pluronic PE 10500",
        "Low Foam Emulsifier",
        "SC, SE",
        False,
    ),
    (
        "STAGWET SW60",
        "stagwet-sw60",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGWET SW60",
        "Rhodafac RE 610",
        "Super Wetting Agent",
        "SC, EC",
        False,
    ),
    (
        "STAGSURF SC 9200",
        "stagsurf-sc-9200",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF SC 9200",
        "Proprietary",
        "Dispersing/Emulsifying",
        "SC",
        False,
    ),
    (
        "STAGSURF AC 6600",
        "stagsurf-ac-6600",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF AC 6600",
        "Proprietary",
        "Emulsifier/Dispersant",
        "SC, CS",
        False,
    ),
    (
        "STAGSURF G5000",
        "stagsurf-g5000",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF G5000",
        "Atplus G5000",
        "Dispersant/wetter/Emulsifier",
        "SC, SE, DC, EW, ME",
        False,
    ),
    (
        "STAGSURF 1306",
        "stagsurf-1306",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGSURF 1306",
        "Hostaphat 1306",
        "Anionic wetting agent Stabilizer",
        "SC, OD",
        False,
    ),
    (
        "STAGWET EP1056",
        "stagwet-ep1056",
        "emulsifier-wetter-dispersant-sc",
        Product.FormulationType.SC,
        "STAGWET EP1056",
        "Ethylan NS 500 LQ",
        "Dispersing agent/Stabilizer",
        "SC",
        False,
    ),
    # Two Component System for All SC Formulations
    (
        "STAGSURF SC 4894",
        "stagsurf-sc-4894",
        "two-component-all-sc",
        Product.FormulationType.SC,
        "STAGSURF SC 4894",
        "Altox 4894/Tersperse 4894",
        "Wetting and Dispersing",
        "All SC Formulations",
        False,
    ),
    (
        "STAGSURF SC 4913",
        "stagsurf-sc-4913",
        "two-component-all-sc",
        Product.FormulationType.SC,
        "STAGSURF SC 4913",
        "Altox 4913/Tersperse 2500",
        "Dispersing",
        "All SC Formulations",
        False,
    ),
    # Single Component System for Various SC Formulations
    (
        "STAGSURF SC 6875",
        "stagsurf-sc-6875",
        "single-component-various-sc",
        Product.FormulationType.SC,
        "STAGSURF SC 6875",
        "Proprietary",
        "Wetting and Dispersing",
        "Various SC Formulations",
        True,
    ),
    # Single Component System for Bispyribac 10% Sodium
    (
        "STAGSURF BS 7800",
        "stagsurf-bs-7800",
        "single-component-bispyribac-10",
        Product.FormulationType.SC,
        "STAGSURF BS 7800",
        "",
        "Surfactant cum adjuvant",
        "Bispyribac SC 10%",
        True,
    ),
    # Two Component System for Bispyribac 10% Sodium
    (
        "STAGSURF ISD",
        "stagsurf-isd",
        "two-component-bispyribac-10",
        Product.FormulationType.SC,
        "STAGSURF ISD",
        "Eucarol ISD",
        "Wetting",
        "Bispyribac SC 10%",
        False,
    ),
    (
        "STAGSURF RCS 43",
        "stagsurf-rcs-43",
        "two-component-bispyribac-10",
        Product.FormulationType.SC,
        "STAGSURF RCS 43",
        "Lamfol RCS 43",
        "Dispersing",
        "Bispyribac SC 10%",
        False,
    ),
    # Brochure page 3 — two-component Bispyribac 10% SC
    (
        "STAGSURF VMS",
        "stagsurf-vms",
        "two-component-bispyribac-10",
        Product.FormulationType.SC,
        "STAGSURF VMS",
        "",
        "Surfactant cum adjuvant",
        "Bispyribac SC 10%",
        False,
    ),
    (
        "STAGSURF EPS",
        "stagsurf-eps",
        "two-component-bispyribac-10",
        Product.FormulationType.SC,
        "STAGSURF EPS",
        "",
        "Surfactant cum adjuvant",
        "Bispyribac SC 10%",
        False,
    ),
    # Two Component System for Bispyribac 40% Sodium
    (
        "STAGSURF AC 7881",
        "stagsurf-ac-7881",
        "two-component-bispyribac-40",
        Product.FormulationType.SC,
        "STAGSURF AC 7881",
        "Proprietary",
        "Dispersing/Emulsifying",
        "Bispyribac SC 40%",
        False,
    ),
    (
        "STAGSURF DW 7200",
        "stagsurf-dw-7200",
        "two-component-bispyribac-40",
        Product.FormulationType.SC,
        "STAGSURF DW 7200",
        "Proprietary",
        "Wetting",
        "Bispyribac SC 40%",
        False,
    ),
    # Emulsifier/Wetter/Dispersant for EC Formulations
    (
        "STAGSURF DS 90 M",
        "stagsurf-ds-90-m",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF DS 90 M",
        "Noigen AB 90(M)/UNITOP AB 91 M",
        "Emulsifier",
        "EC",
        False,
    ),
    (
        "STAGSURF WT 100",
        "stagsurf-wt-100",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF WT 100",
        "Noigen EA 100",
        "Emulsifier/Dispersant/Wetting",
        "EC",
        False,
    ),
    (
        "STAGSURF PO 1000",
        "stagsurf-po-1000",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF PO 1000",
        "Triton X 100",
        "Emulsifier, Wetter",
        "EC",
        False,
    ),
    (
        "STAGSURF EC 400",
        "stagsurf-ec-400",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF EC 400",
        "Etocas 40",
        "Emulsifier",
        "EC",
        False,
    ),
    (
        "STAGSURF EC 3418",
        "stagsurf-ec-3418",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF EC 3418",
        "Alkamuls SC 242/Atlox 3418",
        "Emulsifier",
        "EC",
        False,
    ),
    # Brochure page 3 — general emulsifier pair for EC
    (
        "STAGSURF GE5221",
        "stagsurf-ge5221",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF GE5221",
        "",
        "Proprietary",
        "General EC",
        False,
    ),
    (
        "STAGSURF GE5222",
        "stagsurf-ge5222",
        "emulsifier-wetter-dispersant-ec",
        Product.FormulationType.EC,
        "STAGSURF GE5222",
        "",
        "Proprietary",
        "General EC",
        False,
    ),
    # Emulsifier/Dispersant for ME Formulation
    (
        "STAGSURF 1284",
        "stagsurf-1284",
        "emulsifier-dispersant-me",
        Product.FormulationType.ME,
        "STAGSURF 1284",
        "Termul 1284",
        "Emulsifier",
        "Micro Emulsion",
        False,
    ),
    (
        "STAGSURF 1285",
        "stagsurf-1285",
        "emulsifier-dispersant-me",
        Product.FormulationType.ME,
        "STAGSURF 1285",
        "Termul 1285",
        "Emulsifier",
        "Micro Emulsion",
        False,
    ),
    # Emulsifier/Dispersant for CS Formulation
    (
        "STAGSURF CS 1000",
        "stagsurf-cs-1000",
        "emulsifier-dispersant-cs",
        Product.FormulationType.OTHER,
        "STAGSURF CS 1000",
        "Proprietary",
        "Emulsifier",
        "CS",
        False,
    ),
    (
        "STAGSURF CS 2000",
        "stagsurf-cs-2000",
        "emulsifier-dispersant-cs",
        Product.FormulationType.OTHER,
        "STAGSURF CS 2000",
        "Proprietary",
        "Emulsifier",
        "CS",
        False,
    ),
    # Emulsifier/Dispersant for EW Formulation
    (
        "STAGSURF PEW",
        "stagsurf-pew",
        "emulsifier-dispersant-ew",
        Product.FormulationType.EW,
        "STAGSURF PEW",
        "Proprietary",
        "Wetting and Dispersing",
        "Pretilachlor EW",
        False,
    ),
    # Penetrant/Wetting Agent
    (
        "STAGWET DW 7500",
        "stagwet-dw-7500",
        "penetrant-wetting-dry-wet",
        Product.FormulationType.WETTING,
        "STAGWET DW 7500",
        "Lankropol KPH 70",
        "Penetrant and Wetting",
        "Dry and Wet Formulations",
        False,
    ),
    # Single Component System Emulsifier for Glufosinate SL
    (
        "STAGSURF GF 8800",
        "stagsurf-gf-8800",
        "single-component-glufosinate-sl",
        Product.FormulationType.OTHER,
        "STAGSURF GF 8800",
        "Proprietary",
        "Emulsifier",
        "SL",
        False,
    ),
    # Wetter and Dispersant for Dry Formulations
    (
        "STAGSURF DN",
        "stagsurf-dn",
        "wetter-dispersant-dry-formulations",
        Product.FormulationType.DISPERSING,
        "STAGSURF DN",
        "Tamol DN",
        "Dispersant",
        "WP, WDG",
        False,
    ),
    (
        "STAGSURF FB100",
        "stagsurf-fb100",
        "wetter-dispersant-dry-formulations",
        Product.FormulationType.DISPERSING,
        "STAGSURF FB100",
        "Tamol FBP1",
        "Dispersant/Wetter",
        "WP, WDG",
        False,
    ),
    (
        "STAGWET SDS",
        "stagwet-sds",
        "wetter-dispersant-dry-formulations",
        Product.FormulationType.WETTING,
        "STAGWET SDS",
        "Gerapon SDS",
        "Penetrating/Wetting Agent",
        "Dry and Wet Formulations",
        False,
    ),
    (
        "STAGSURF PS",
        "stagsurf-ps",
        "wetter-dispersant-dry-formulations",
        Product.FormulationType.DISPERSING,
        "STAGSURF PS",
        "IGSURF 2333PS/Dispersol PS-PW-TH",
        "Dispersant",
        "Water Dispersible Powder",
        False,
    ),
    # Proprietary Blends / Tank Mix Adjuvants (brochure page 3)
    (
        "STAGPENT 1000 UT",
        "stagpent-1000-ut",
        "proprietary-blends",
        Product.FormulationType.ADJUVANT,
        "STAGPENT 1000 UT",
        "OUTRIGHT",
        "Proprietary Adjuvant",
        "Topramezone SC",
        True,
    ),
    (
        "STAGPENT 1000 UTE",
        "stagpent-1000-ute",
        "proprietary-blends",
        Product.FormulationType.ADJUVANT,
        "STAGPENT 1000 UTE",
        "",
        "Proprietary Adjuvant",
        "Topramezone SC",
        False,
    ),
    (
        "STAGPENT TMBO",
        "stagpent-tmbo",
        "proprietary-blends",
        Product.FormulationType.ADJUVANT,
        "STAGPENT TMBO",
        "",
        "Proprietary Adjuvant",
        "Tembotrione SC",
        True,
    ),
    (
        "EMPARA",
        "empara",
        "proprietary-blends",
        Product.FormulationType.ADJUVANT,
        "EMPARA",
        "",
        "Emulsified paraffin Oil based adjuvant",
        "Herbicides, OD formulations",
        False,
    ),
    (
        "METRANS",
        "metrans",
        "proprietary-blends",
        Product.FormulationType.ADJUVANT,
        "METRANS",
        "",
        "Methyl Ester based penetrating agent",
        "Herbicides, OD formulations",
        False,
    ),
    # Textile — Mercerisation
    (
        "Stagmer MW",
        "stagmer-mw",
        "textile-mercerisation",
        Product.FormulationType.TEXTILE,
        "Stagmer MW",
        "",
        "Mercerising cum Causticizing Agent",
        "Cotton and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagmer MLF",
        "stagmer-mlf",
        "textile-mercerisation",
        Product.FormulationType.TEXTILE,
        "Stagmer MLF",
        "",
        "Low Foam Mercerising cum Causticizing Agent",
        "Cotton and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagmer MR",
        "stagmer-mr",
        "textile-mercerisation",
        Product.FormulationType.TEXTILE,
        "Stagmer MR",
        "",
        "Mercerising cum Causticizing Agent",
        "High thread count cotton and blends — 100 Kg packing",
        False,
    ),
    # Textile — Wetting/Scouring/Stain Removing
    (
        "Stagwet 7X",
        "stagwet-7x",
        "textile-wetting-scouring",
        Product.FormulationType.TEXTILE,
        "Stagwet 7X",
        "",
        "Powerful Wetting Agent",
        "All types of fibres — 100 Kg packing",
        False,
    ),
    (
        "Stagwet AP 100",
        "stagwet-ap-100",
        "textile-wetting-scouring",
        Product.FormulationType.TEXTILE,
        "Stagwet AP 100",
        "",
        "Concentrated Anionic Wetting Agent",
        "Cellulose and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagwet XNI",
        "stagwet-xni",
        "textile-wetting-scouring",
        Product.FormulationType.TEXTILE,
        "Stagwet XNI",
        "",
        "Scouring cum Stain Removing Agent",
        "Polyester and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagwet HPW",
        "stagwet-hpw",
        "textile-wetting-scouring",
        Product.FormulationType.TEXTILE,
        "Stagwet HPW",
        "",
        "Low Foaming Wetting cum Scouring Agent",
        "Fibres/Yarn/Knits — 100 Kg packing",
        False,
    ),
    (
        "Stagwet RW",
        "stagwet-rw",
        "textile-wetting-scouring",
        Product.FormulationType.TEXTILE,
        "Stagwet RW",
        "",
        "Deaerating Agent",
        "Denim and package dyeing — 100 Kg packing",
        False,
    ),
    # Textile — Dyeing Aids
    (
        "Stagfix NF",
        "stagfix-nf",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagfix NF",
        "",
        "Non Formaldehyde Dye Fixing Agent",
        "Cellulose and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagfix HCF",
        "stagfix-hcf",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagfix HCF",
        "",
        "Concentrated Formaldehyde Free Dye Fixing Agent",
        "Cellulose and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagfix FC70",
        "stagfix-fc70",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagfix FC70",
        "",
        "Dye Fixing Agent",
        "All cellulose and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagwash",
        "stagwash",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagwash",
        "",
        "Washing off Agent",
        "Reactive/Direct dyes — 100 Kg packing",
        False,
    ),
    (
        "Stagsoap",
        "stagsoap",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagsoap",
        "",
        "Anionic Soaping Agent",
        "Reactive and direct dyes — 100 Kg packing",
        False,
    ),
    (
        "Stagvel",
        "stagvel",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagvel",
        "",
        "Levelling Agent",
        "Cotton and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagsperse 50",
        "stagsperse-50",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagsperse 50",
        "",
        "Dispersing cum Levelling Agent",
        "Synthetic fibre/filaments — 100 Kg packing",
        False,
    ),
    (
        "Star Magic",
        "star-magic",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Star Magic",
        "",
        "Levelling/Relevelling/Stripping Agent",
        "Polyester and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagsperse FBSN",
        "stagsperse-fbsn",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagsperse FBSN",
        "",
        "Washing off Agent",
        "Cellulose and blends — 100 Kg packing",
        False,
    ),
    (
        "Stagsoap Conc.",
        "stagsoap-conc",
        "textile-dyeing-aids",
        Product.FormulationType.TEXTILE,
        "Stagsoap Conc.",
        "",
        "Concentrated Washing off Agent",
        "Reactive and direct dyes — 100 Kg packing",
        False,
    ),
    # Textile — Finishing Agents
    (
        "Stasoft OC",
        "stasoft-oc",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft OC",
        "",
        "Non-Yellowing Cationic Softener",
        "All types of fibres and blends — 100 Kg packing",
        False,
    ),
    (
        "Stasoft CWS",
        "stasoft-cws",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft CWS",
        "",
        "Cold Water-Soluble Cationic Softener",
        "All types of fibres and blends — 100 Kg packing",
        False,
    ),
    (
        "Stasoft Conc",
        "stasoft-conc",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft Conc",
        "",
        "Cationic Softener",
        "Bulky and fluffy feel — 100 Kg packing",
        False,
    ),
    (
        "Stasoft RW",
        "stasoft-rw",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft RW",
        "",
        "Reactive Softener",
        "All types of fibres — 100 Kg packing",
        False,
    ),
    (
        "Stasilk AMS",
        "stasilk-ams",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasilk AMS",
        "",
        "Amino Silicone Softener",
        "Silky feel for all types of fibres — 100 Kg packing",
        False,
    ),
    (
        "Stabulk SW",
        "stabulk-sw",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stabulk SW",
        "",
        "Silicone Softener",
        "Bulky and bouncy feel — 100 Kg packing",
        False,
    ),
    (
        "Star PEW",
        "star-pew",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Star PEW",
        "",
        "PE Wax Emulsion",
        "Excellent shining and lubricity — 100 Kg packing",
        False,
    ),
    (
        "Stafeel HP",
        "stafeel-hp",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stafeel HP",
        "",
        "Hydrophilic Non-Yellowing Cationic Softener",
        "Terry towel and knits — 100 Kg packing",
        False,
    ),
    (
        "Stafeel TCH",
        "stafeel-tch",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stafeel TCH",
        "",
        "Hydrophilic Silicone Softener",
        "Terry towel and hosiery fabric — 100 Kg packing",
        False,
    ),
    (
        "Stasoft NIS",
        "stasoft-nis",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft NIS",
        "",
        "Non-Ionic Softener",
        "All types of fibres and filaments — 100 Kg packing",
        False,
    ),
    (
        "Stasoft NIS Conc.",
        "stasoft-nis-conc",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft NIS Conc.",
        "",
        "Concentrated Non-Ionic Softener",
        "All types of substrates — 100 Kg packing",
        False,
    ),
    (
        "Stasoft LCS",
        "stasoft-lcs",
        "textile-finishing-agents",
        Product.FormulationType.TEXTILE,
        "Stasoft LCS",
        "",
        "Concentrated Liquid Cationic Softener",
        "Silky and fluffy feel — 100 Kg packing",
        False,
    ),
]

SITE_SETTINGS = {
    "site_name": "Star Agsurf Industries",
    "tagline": "Specialty Surfactants & Agrochemical Formulations",
    "about_us": (
        "Star Agsurf Industries is a leader in specialty chemical manufacturing for "
        "agriculture. With expertise in surfactant chemistry and agrochemical "
        "formulations, we deliver solutions that enhance crop protection, nutrient "
        "absorption, and application efficiency."
    ),
    "vision": (
        "To be recognized globally as a premium partner in agrochemical formulations, "
        "known for innovation, integrity, and sustainability."
    ),
    "mission": (
        "To empower agriculture with high-performance specialty chemicals that balance "
        "productivity with environmental responsibility."
    ),
    "manufacturing_expertise": (
        "Expertise in SC, EC, ME, EW, CS, and SL formulation systems with "
        "client-centric custom formulation capabilities."
    ),
    "rd_focus": (
        "Continuous innovation in wetting, dispersing, and adjuvant technologies with "
        "benchmarking against global competitors."
    ),
    "sustainability": (
        "Committed to eco-conscious formulations and environmentally responsible manufacturing."
    ),
    "client_commitment": (
        "Partnering with distributors and manufacturers worldwide through technical "
        "documentation, formulation support, and collaborative partnerships."
    ),
    "contact_email": "marketing.stagsurf@gmail.com",
    "contact_phone": "+91 83699 20148",
}

# slug -> {properties, benefits, applications, description}
PRODUCT_TDS = {
    "stagpent-1000-ut": {
        "description": (
            "<p>Stagpent 1000 UT is a spray adjuvant for Topramezone SC. It is a one-drum "
            "solution combining wetters, oils, and ammonium sulphate to significantly increase "
            "herbicide performance.</p>"
            "<p>Stagpent is a mix of methyl ester, non-ionic surfactants, and ammonium "
            "sulphates. The methyl ester is a penetrating oil that helps active ingredients "
            "penetrate the weed's waxy cuticle and reduces surface evaporation. Non-ionic "
            "surfactants help spray droplets adhere and spread across the target. Ammonium "
            "sulphate minimizes hard water effects on susceptible herbicides.</p>"
        ),
        "properties": [
            ("Product Type", "Spray Adjuvant"),
            ("Application", "Topramezone SC"),
            ("Composition", "Methyl Ester, Non-Ionic Surfactants, Ammonium Sulphate"),
        ],
        "benefits": [
            "Increases penetration of herbicides through waxy weed cuticles",
            "Delays the dry down rate of spray droplets on weeds",
            "Assists in the retention of spray droplets on weed surfaces",
            "Increases the wetting and spreading of spray droplets on weed surfaces",
            "Reduces hard water deactivation of susceptible herbicides e.g. Glyphosates",
            "High quality formulation providing easy dispersion and stable emulsion in tank mixes",
        ],
        "applications": ["Topramezone SC", "Crop Protection", "Herbicide Tank Mixes"],
    },
    "stagpent-tmbo": {
        "description": (
            "<p>Stagpent TMBO is a penetrating spray adjuvant to enhance the activity of "
            "Tembotrione SC. Active ingredient contains modified vegetable oil and surfactant "
            "blend.</p>"
            "<p>The oil-based adjuvant combines methylated seed oil with non-ionic surfactants "
            "for good spreading, excellent deposition, and penetration through waxy plant "
            "cuticles. It also reduces spray droplet evaporation rates and drift.</p>"
        ),
        "properties": [
            ("Appearance", "Clear Pale Yellow to Yellow Liquid"),
            ("pH", "5 to 7"),
            ("Solid Content", "Min 95%"),
            ("Solubility in Water", "Dispersion/Emulsion"),
        ],
        "benefits": [
            "Enhances activity of Tembotrione SC",
            "Good spreading and excellent deposition on target surfaces",
            "Penetration through waxy plant cuticles",
            "Reduces spray droplet evaporation rates",
            "Reduces drift",
        ],
        "applications": ["Tembotrione SC", "Crop Protection"],
    },
    "stagsurf-bs-7800": {
        "description": (
            "<p>Stagsurf BS 7800 is a single component emulsifier for Bispyribac SC 10% "
            "sodium, engineered via sophisticated synthesis routes for superior performance.</p>"
            "<p><strong>Guideline Recipe (per 100 gm):</strong></p>"
            "<ul>"
            "<li>Technical: 10.2 gm</li>"
            "<li>Stagsurf BS 7800: 85.0 gm</li>"
            "<li>Pure MEG: 3.80 gm</li>"
            "<li>Silica (Aerosil 200): 0.50 gm</li>"
            "<li>Defoamer: 0.50 gm</li>"
            "</ul>"
        ),
        "properties": [
            ("Product Type", "Single Component Emulsifier"),
            ("Target Formulation", "Bispyribac SC 10% Sodium"),
        ],
        "benefits": [
            "Minimum separation in formulation",
            "No settling or hardening of formulation",
            "Desired viscosity can be achieved easily",
            "Upon dilution suspension is like micro-emulsion for fine particle size",
            "Better penetration and translocation showing best field efficacy",
            "Cost effective",
        ],
        "applications": ["Bispyribac SC 10% Sodium", "Crop Protection"],
    },
    "stagsurf-sc-6875": {
        "description": (
            "<p>STAGSURF SC 6875 is a single component surfactant system for SC formulations. "
            "Highly recommended for high load SCs, challenging actives, and crucial SC "
            "combinations. Works at very low dosage with no co-dispersing or wetting agent required.</p>"
        ),
        "properties": [
            ("Appearance", "Pale yellow viscous liquid"),
            ("pH (1% aq. sol)", "6 to 9"),
            ("Ionic Character", "Anionic"),
            ("Solubility", "Soluble in water"),
        ],
        "benefits": [
            "Single component system — no co-dispersing or wetting agent needed",
            "Works at very low dosage",
            "Recommended for high load SCs and challenging actives",
            "Suitable for crucial combination SC formulations",
        ],
        "applications": [
            "Metribuzin 600 gm/l SC (4%)",
            "Imidacloprid 48 SC (3%)",
            "Pyraclostrobin 30 SC (2%)",
            "Tebuconazole 43 SC (2%)",
            "Carbendazim 42.20 SC (3%)",
            "Prothioconazole 20 + Tebuconazole 20 SC (5%)",
            "Azoxystrobin 18.2 + Difenconazole 11.4 SC (4%)",
            "Azoxystrobin 11 + Tebuconazole 18.3 SC (4%)",
        ],
    },
}


# Products from brochure pages 4–5 ("Products vs Competition" table only).
# Excludes pages 1–3 content (company overview, portfolio, specialty products).
BROCHURE_COMPARISON_SLUGS = frozenset(
    {
        "stagspread-4080",
        "stagsurf-425",
        "stagsurf-pd-137",
        "stagwet-sls",
        "stagwet-aos",
        "stagsurf-ag810",
        "stagwet-wt-7200",
        "stagwet-roe60",
        "stagsurf-ds-90-m",
        "stagsurf-wt-100",
        "stagsurf-po-1000",
        "stagsurf-ec-400",
        "stagsurf-ec-3418",
        "stagsurf-tae",
        "stagsurf-ntae",
        "stagsurf-d33",
        "stagsurf-tfl",
        "stagsurf-tflk",
        "stagsurf-483",
        "stagsurf-tsu",
        "stagsurf-ep-140",
        "stagsurf-ep-150",
        "stagwet-sw60",
        "stagsurf-sc-9200",
        "stagsurf-ac-6600",
        "stagsurf-g5000",
        "stagsurf-1306",
        "stagwet-ep1056",
    }
)

# Products from brochure page 3 ("Our specialty products" list only).
# Excludes pages 1–2 (company overview / portfolio marketing text).
BROCHURE_SPECIALTY_SLUGS = frozenset(
    {
        "stagsurf-sc-6875",
        "stagsurf-bs-7800",
        "stagsurf-vms",
        "stagsurf-eps",
        "stagsurf-ac-7881",
        "stagsurf-dw-7200",
        "stagsurf-ge5221",
        "stagsurf-ge5222",
        "stagpent-1000-ut",
        "stagpent-1000-ute",
        "stagpent-tmbo",
        "empara",
        "metrans",
        "stagsurf-gf-8800",
        "stagsurf-pew",
    }
)

# All brochure product pages (3 + 4 + 5) — 43 unique products.
BROCHURE_PRODUCT_SLUGS = BROCHURE_COMPARISON_SLUGS | BROCHURE_SPECIALTY_SLUGS


def build_short_description(name, function, equivalent, formulation):
    parts = [f"{name} — {function}."]
    if equivalent:
        parts.append(f"Equivalent: {equivalent}.")
    parts.append(f"For {formulation}.")
    return " ".join(parts)
