# Generated by Django 5.2.15 on 2026-06-15 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_company_logo_sitesettings_twitter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mission',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
